---
- name: print containers
  hosts: all
  tasks:
    - name: get containers
      docker_host_info:
        containers: yes
      register: docker_info

    - name: print info
      debug:
        msg: "{{docker_info}}"
