---
- name: Pwsh test
  hosts: all
  become: true
  tasks:
    - name: Execute renew PAT script
      ansible.windows.win_powershell:
        script: |
          New-Item -ItemType File -Path ".\newfile.txt"
