---
- name: Pwsh test
  hosts: all
  become: true
  tasks:
    - name: Execute renew PAT script
      shell:
        cmd: ls -l
      register: info

    - name: haha
      debug:
        msg: "{{ info }}"
