---
- name: Renew Secret
  hosts: localhost
  tasks:
    - name: Log in to Azure
      ansible.builtin.shell:
        cmd: az login --user {{ USERNAME }} --password {{ PASSWORD }}

    - name: Execute renew secret
      ansible.builtin.shell:
        cmd: |
          SP_SECRET=$(az ad app credential reset --id "{{ service_principal }}" --query password -o tsv)
